/*
Comando para carga masiva
sqlldr EDSONG 'C:\Users\User\OneDrive\Desktop\control-control.ctl' log = track.log skip=1
*/
CREATE TABLE Carga (
  NOMBRE_ELECCION  VARCHAR2(80),
  ANIO_ELECCION  number,
  PAIS VARCHAR2(80),
  REGION VARCHAR2(80),
  DEPTO VARCHAR2(80),
  MUNICIPIO VARCHAR2(80),
  PARTIDO VARCHAR2(80),
  NOMBRE_PARTIDO VARCHAR2(80),
  SEXO VARCHAR2(80),
  RAZA VARCHAR2(80),
  ANALFABETOS  number,
  ALFABETOS number,
  SEXO2 VARCHAR2(80),
  RAZA2 VARCHAR2(80),
  PRIMARIA number,
  NIVEL_MEDIO number,
  UNIVERSITARIOS number
)
select count(*)   from carga;
select * from carga;
DELETE carga;

/*
Creacion de Tablas del modelo
*/
CREATE TABLE Pais(
    idPais int GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL,
    PRIMARY KEY(idPais)
);
CREATE TABLE Region(
    idRegion int GENERATED BY DEFAULT AS IDENTITY,
    idPais int not null,
    nombre VARCHAR2(50) NOT NULL,
    PRIMARY KEY(idRegion),
    FOREIGN KEY (idPais) REFERENCES Pais(idPais)
);
CREATE TABLE Departamento(
    idDepartamento int GENERATED BY DEFAULT AS IDENTITY,
    idRegion int not null,
    nombre VARCHAR2(100) NOT NULL,
    PRIMARY KEY(idDepartamento),
    FOREIGN KEY (idRegion) REFERENCES Region(idRegion)
)
CREATE TABLE Municipio(
    idMunicipio int GENERATED BY DEFAULT AS IDENTITY,
    idDepartamento int not null,
    nombre VARCHAR2(100) NOT NULL,
    PRIMARY KEY(idMunicipio),
    FOREIGN KEY (idDepartamento) REFERENCES Departamento(idDepartamento)
)
create table Eleccion(
    idEleccion int GENERATED BY DEFAULT AS IDENTITY,    
    nombre VARCHAR2(100) NOT NULL,
    anio int,
    PRIMARY KEY(idEleccion)
)
create table Partido(
    idPartido int GENERATED BY DEFAULT AS IDENTITY,    
    partido VARCHAR2(100) NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    PRIMARY KEY(idPartido)
)
CREATE TABLE EleccionPartido(
    idEleccioPartido int GENERATED BY DEFAULT AS IDENTITY,
    idEleccion int not null,
    idPartido int not null,
    PRIMARY KEY(idEleccioPartido),
    FOREIGN KEY (idEleccion) REFERENCES Eleccion(idEleccion),
    FOREIGN KEY (idPartido) REFERENCES Partido(idPartido)
)
create table Sexo(
    idSexo int GENERATED BY DEFAULT AS IDENTITY,    
    nombre VARCHAR2(100) NOT NULL,
    PRIMARY KEY(idSexo)
)
create table Raza(
    idRaza int GENERATED BY DEFAULT AS IDENTITY,    
    nombre VARCHAR2(100) NOT NULL,
    PRIMARY KEY(idRaza)
)
create table conteoVoto(
    idConteo int GENERATED BY DEFAULT AS IDENTITY,    
    alfabeto int,
    analfabeto int,
    primaria int,
    nivel_medio int,
    universitarios int,
    idRaza int not null,
    idSexo int not null,
    idMunicipio int not null,
    idPartido int not null,
    PRIMARY KEY(idConteo),
    FOREIGN KEY (idRaza) REFERENCES Raza(idRaza),
    FOREIGN KEY (idSexo) REFERENCES Sexo(idSexo),
    FOREIGN KEY (idMunicipio) REFERENCES Municipio(idMunicipio),
    FOREIGN KEY (idPartido) REFERENCES Partido(idPartido)
)